import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { Article } from "@/lib/models/Article";

export const dynamic = "force-dynamic";

const articles = [
  { title: "bKash: How a Mobile Wallet Transformed Bangladesh's Financial Inclusion", slug: "bkash-mobile-wallet-bangladesh-financial-inclusion", excerpt: "From a small mobile banking startup to serving over 65 million users, bKash's journey is a masterclass in fintech innovation for emerging markets.", content: "bKash Limited, a subsidiary of BRAC Bank, has become one of the most successful mobile financial services in the world. Founded in 2011 by Kamal Quadir, bKash started with a simple mission: bring banking to the unbanked population of Bangladesh. Today, it processes billions of dollars in transactions monthly, enabling millions of Bangladeshis to send money, pay bills, and access financial services from their mobile phones.", category: "Fintech", author: "Rahim Chowdhury", authorAvatar: "https://randomuser.me/api/portraits/men/32.jpg", coverImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800", publishedAt: "2026-04-10", readTime: 7, featured: true, tags: ["fintech", "bKash", "financial inclusion"] },
  { title: "Pathao's Rise: From Ride-Sharing to Bangladesh's Super App", slug: "pathao-rise-ride-sharing-super-app-bangladesh", excerpt: "How Pathao evolved from a simple parcel delivery service into Bangladesh's most-used super app covering rides, food, and digital payments.", content: "Pathao began in 2015 as a simple courier service in Dhaka. Within two years, it had pivoted to motorcycle ride-sharing, solving one of Dhaka's most pressing problems — traffic congestion. By 2018, Pathao had expanded to food delivery and digital payments, attracting investment from Go-Jek and other regional players.", category: "Technology", author: "Nadia Islam", authorAvatar: "https://randomuser.me/api/portraits/women/44.jpg", coverImage: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800", publishedAt: "2026-04-09", readTime: 6, featured: true, tags: ["Pathao", "ride-sharing", "super app"] },
  { title: "Chaldal: Delivering Groceries in Under an Hour Across Dhaka", slug: "chaldal-grocery-delivery-dhaka-bangladesh", excerpt: "Chaldal's operational excellence and micro-warehouse model has made it the blueprint for emerging market e-commerce logistics.", content: "Founded in 2013 by Waseem Alim and Tejas Viswanath, Chaldal set out to solve a simple problem: grocery shopping in Dhaka is time-consuming and exhausting. By building a network of micro-warehouses across the city, Chaldal can deliver fresh groceries in under an hour.", category: "E-commerce", author: "Karim Hossain", authorAvatar: "https://randomuser.me/api/portraits/men/55.jpg", coverImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800", publishedAt: "2026-04-08", readTime: 5, featured: false, tags: ["Chaldal", "e-commerce", "grocery"] },
  { title: "ShopUp: Empowering Bangladesh's 10 Million Small Retailers", slug: "shopup-empowering-small-retailers-bangladesh", excerpt: "ShopUp is digitizing Bangladesh's massive informal retail sector, giving small shop owners access to credit, inventory, and digital tools.", content: "Bangladesh has over 10 million small retailers — the backbone of its consumer economy. ShopUp, founded by Afeef Zaman and Ataur Rahim Chowdhury, is building the infrastructure to bring these retailers into the digital economy. The company has raised over $75 million and is expanding rapidly across South Asia.", category: "B2B Tech", author: "Sadia Rahman", authorAvatar: "https://randomuser.me/api/portraits/women/28.jpg", coverImage: "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=800", publishedAt: "2026-04-07", readTime: 6, featured: true, tags: ["ShopUp", "retail", "B2B"] },
  { title: "Shohoz: Redefining Urban Mobility and Logistics in Bangladesh", slug: "shohoz-urban-mobility-logistics-bangladesh", excerpt: "From bus ticketing to ride-sharing and logistics, Shohoz has become one of Bangladesh's most versatile tech platforms.", content: "Maliha Quadir founded Shohoz in 2014 with a vision to make transportation accessible and efficient for all Bangladeshis. Starting with online bus ticketing, Shohoz quickly expanded into ride-sharing and logistics.", category: "Mobility", author: "Tanvir Ahmed", authorAvatar: "https://randomuser.me/api/portraits/men/67.jpg", coverImage: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800", publishedAt: "2026-04-06", readTime: 5, featured: false, tags: ["Shohoz", "mobility", "logistics"] },
  { title: "The Garment Industry's Digital Revolution: How Tech is Transforming RMG", slug: "garment-industry-digital-revolution-bangladesh-rmg", excerpt: "Bangladesh's $40 billion garment industry is undergoing a digital transformation with startups building tools for compliance and sustainability.", content: "Bangladesh's Ready-Made Garment sector employs over 4 million workers and accounts for 84% of the country's export earnings. Now, a new wave of tech startups is transforming this traditional industry with platforms for supply chain transparency and sustainable manufacturing.", category: "Industry", author: "Farhana Begum", authorAvatar: "https://randomuser.me/api/portraits/women/61.jpg", coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800", publishedAt: "2026-04-05", readTime: 8, featured: false, tags: ["RMG", "garment", "sustainability"] },
  { title: "10 Minute School: Making Quality Education Accessible to All Bangladeshis", slug: "10-minute-school-education-bangladesh", excerpt: "Ayman Sadiq's 10 Minute School has become the largest online education platform in Bangladesh with over 7 million students.", content: "Ayman Sadiq started 10 Minute School in 2015 with a simple Facebook page and a mission to make quality education accessible to every student in Bangladesh. Today it is the country's largest online education platform with over 7 million registered users.", category: "Edtech", author: "Rahim Chowdhury", authorAvatar: "https://randomuser.me/api/portraits/men/32.jpg", coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800", publishedAt: "2026-04-04", readTime: 6, featured: false, tags: ["10 Minute School", "edtech", "education"] },
  { title: "Nagad: The Government-Backed MFS That Challenged bKash", slug: "nagad-government-mfs-challenged-bkash-bangladesh", excerpt: "Bangladesh Post Office's digital financial service Nagad grew to 80 million users in just 4 years, disrupting the mobile money market.", content: "Launched in 2019 by Bangladesh Post Office in partnership with Third Wave Technologies, Nagad quickly became one of the fastest-growing mobile financial services in the world, attracting over 80 million users within four years.", category: "Fintech", author: "Nadia Islam", authorAvatar: "https://randomuser.me/api/portraits/women/44.jpg", coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800", publishedAt: "2026-04-03", readTime: 5, featured: false, tags: ["Nagad", "fintech", "mobile money"] },
  { title: "Bangladesh's Agritech Revolution: Connecting Farmers to Markets", slug: "bangladesh-agritech-revolution-farmers-markets", excerpt: "A new generation of agritech startups is using AI and mobile technology to help Bangladesh's 16 million farming households get fair prices.", content: "Agriculture employs nearly 40% of Bangladesh's workforce, yet farmers often receive only a fraction of the final market price. Startups like iFarmer are changing this by connecting farmers directly to buyers through digital platforms.", category: "Agritech", author: "Karim Hossain", authorAvatar: "https://randomuser.me/api/portraits/men/55.jpg", coverImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800", publishedAt: "2026-04-02", readTime: 7, featured: false, tags: ["agritech", "farming", "iFarmer"] },
  { title: "Shajgoj: Building Bangladesh's Largest Beauty and Lifestyle Platform", slug: "shajgoj-beauty-lifestyle-platform-bangladesh", excerpt: "Shajgoj has grown from a beauty blog to Bangladesh's leading e-commerce platform for beauty and personal care products.", content: "Founded by Rayana Hossain in 2012, Shajgoj started as a beauty blog before evolving into Bangladesh's premier beauty e-commerce platform with thousands of local and international products.", category: "E-commerce", author: "Sadia Rahman", authorAvatar: "https://randomuser.me/api/portraits/women/28.jpg", coverImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800", publishedAt: "2026-04-01", readTime: 5, featured: false, tags: ["Shajgoj", "beauty", "e-commerce"] },
  { title: "Bangladesh's Startup Ecosystem: $1 Billion in Funding and Growing", slug: "bangladesh-startup-ecosystem-billion-funding", excerpt: "Bangladesh's startup ecosystem has crossed $1 billion in total funding, with fintech, e-commerce, and logistics leading the charge.", content: "Bangladesh's startup ecosystem has matured significantly. From a handful of early-stage companies in 2015, the ecosystem now boasts over 1,500 active startups and has attracted over $1 billion in venture capital funding.", category: "Investment", author: "Tanvir Ahmed", authorAvatar: "https://randomuser.me/api/portraits/men/67.jpg", coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800", publishedAt: "2026-03-30", readTime: 8, featured: true, tags: ["startup ecosystem", "venture capital", "investment"] },
  { title: "Maya: AI-Powered Health Assistant Serving Millions of Bangladeshis", slug: "maya-ai-health-assistant-bangladesh", excerpt: "Maya's AI-powered health platform provides free medical advice to millions of Bangladeshis who lack access to quality healthcare.", content: "Maya Apa, founded by Ivy Huq Russell, is an AI-powered health assistant that provides free medical advice to Bangladeshis via mobile. With over 5 million users, Maya has become a critical healthcare resource.", category: "Healthtech", author: "Farhana Begum", authorAvatar: "https://randomuser.me/api/portraits/women/61.jpg", coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800", publishedAt: "2026-03-28", readTime: 6, featured: false, tags: ["Maya", "healthtech", "AI"] },
  { title: "Truck Lagbe: Digitizing Bangladesh's $8 Billion Trucking Industry", slug: "truck-lagbe-digitizing-trucking-bangladesh", excerpt: "Truck Lagbe is building the Uber for trucks in Bangladesh, connecting shippers with truck owners through a digital marketplace.", content: "Bangladesh's trucking industry moves billions of dollars worth of goods every year, yet it remains largely informal. Truck Lagbe is changing this by creating a digital marketplace connecting shippers with truck owners.", category: "Logistics", author: "Rahim Chowdhury", authorAvatar: "https://randomuser.me/api/portraits/men/32.jpg", coverImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800", publishedAt: "2026-03-26", readTime: 5, featured: false, tags: ["Truck Lagbe", "logistics", "trucking"] },
  { title: "Women Entrepreneurs Breaking Barriers in Bangladesh's Tech Sector", slug: "women-entrepreneurs-tech-sector-bangladesh", excerpt: "A new generation of women founders is reshaping Bangladesh's technology landscape, from fintech to healthtech and beyond.", content: "Bangladesh has seen a remarkable rise in women-led tech startups. Entrepreneurs like Maliha Quadir, Ivy Huq Russell, and Rayana Hossain have built companies serving millions of users while creating opportunities for other women in tech.", category: "Leadership", author: "Nadia Islam", authorAvatar: "https://randomuser.me/api/portraits/women/44.jpg", coverImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800", publishedAt: "2026-03-24", readTime: 7, featured: false, tags: ["women entrepreneurs", "leadership", "diversity"] },
  { title: "Bangladesh's Freelancing Economy: $700 Million and the World's Second Largest", slug: "bangladesh-freelancing-economy-second-largest", excerpt: "Bangladesh has become the world's second-largest freelancing nation with over 650,000 active freelancers earning hundreds of millions annually.", content: "Bangladesh has quietly become a global powerhouse in the freelancing economy. With over 650,000 active freelancers on platforms like Upwork and Fiverr, Bangladesh earns over $700 million annually from freelancing.", category: "Economy", author: "Karim Hossain", authorAvatar: "https://randomuser.me/api/portraits/men/55.jpg", coverImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800", publishedAt: "2026-03-22", readTime: 6, featured: false, tags: ["freelancing", "digital economy", "remote work"] },
  { title: "SSL Wireless: The Pioneer Behind Bangladesh's Digital Payment Infrastructure", slug: "ssl-wireless-digital-payment-infrastructure-bangladesh", excerpt: "SSL Wireless has been quietly building Bangladesh's digital payment backbone for over two decades, enabling millions of online transactions.", content: "While newer fintech companies grab headlines, SSL Wireless has been the silent backbone of Bangladesh's digital payment infrastructure since 2000. The company processes billions of taka in transactions annually.", category: "Fintech", author: "Sadia Rahman", authorAvatar: "https://randomuser.me/api/portraits/women/28.jpg", coverImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800", publishedAt: "2026-03-20", readTime: 6, featured: false, tags: ["SSL Wireless", "payment gateway", "fintech"] },
];

export async function GET() {
  try {
    await connectDB();
    await Article.deleteMany({});
    await Article.insertMany(articles);
    return NextResponse.json({ success: true, count: articles.length });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
