import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { Startup } from "@/lib/models/Startup";

export const dynamic = "force-dynamic";

const startups = [
  { name: "bKash", slug: "bkash", tagline: "Mobile financial services for all Bangladeshis", description: "bKash is Bangladesh's largest mobile financial service provider, enabling millions to send money, pay bills, and access financial services via mobile phone.", logo: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200", industry: "Fintech", stage: "Growth", founded: "2011", location: "Dhaka", founders: ["Kamal Quadir"], funding: "$250M", website: "https://bkash.com" },
  { name: "Pathao", slug: "pathao", tagline: "Bangladesh's leading super app for rides, food & payments", description: "Pathao started as a motorcycle ride-sharing platform and evolved into Bangladesh's most-used super app covering rides, food delivery, courier, and digital payments.", logo: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=200", industry: "Super App", stage: "Series B", founded: "2015", location: "Dhaka", founders: ["Hussain M Elius", "Fahim Ahmed"], funding: "$12M", website: "https://pathao.com" },
  { name: "Chaldal", slug: "chaldal", tagline: "Groceries delivered in under 1 hour", description: "Chaldal is Bangladesh's first and largest online grocery delivery platform, using a micro-warehouse model to deliver fresh groceries across Dhaka in under one hour.", logo: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=200", industry: "E-commerce", stage: "Series A", founded: "2013", location: "Dhaka", founders: ["Waseem Alim", "Tejas Viswanath"], funding: "$15M", website: "https://chaldal.com" },
  { name: "ShopUp", slug: "shopup", tagline: "Empowering Bangladesh's 10 million small retailers", description: "ShopUp is a B2B commerce platform digitizing Bangladesh's informal retail sector, providing small shop owners with inventory financing, digital ordering, and business analytics.", logo: "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=200", industry: "B2B Tech", stage: "Series B", founded: "2018", location: "Dhaka", founders: ["Afeef Zaman", "Ataur Rahim Chowdhury"], funding: "$75M", website: "https://shopup.com" },
  { name: "Shohoz", slug: "shohoz", tagline: "Redefining mobility and logistics in Bangladesh", description: "Shohoz is a mobility super-platform offering bus ticketing, ride-sharing, and logistics services across Bangladesh, serving millions of users daily.", logo: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=200", industry: "Mobility", stage: "Series A", founded: "2014", location: "Dhaka", founders: ["Maliha Quadir"], funding: "$15M", website: "https://shohoz.com" },
  { name: "10 Minute School", slug: "10-minute-school", tagline: "Quality education for every Bangladeshi student", description: "10 Minute School is Bangladesh's largest online education platform with over 7 million registered students, offering courses for SSC, HSC, and university students.", logo: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200", industry: "Edtech", stage: "Series A", founded: "2015", location: "Dhaka", founders: ["Ayman Sadiq"], funding: "$2M", website: "https://10minuteschool.com" },
  { name: "Maya", slug: "maya", tagline: "AI-powered health assistant for Bangladesh", description: "Maya is an AI-powered health platform providing free medical advice to over 5 million Bangladeshis via mobile, with a focus on women's health and rural communities.", logo: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200", industry: "Healthtech", stage: "Series A", founded: "2016", location: "Dhaka", founders: ["Ivy Huq Russell"], funding: "$5M", website: "https://maya.com.bd" },
  { name: "iFarmer", slug: "ifarmer", tagline: "Connecting farmers to finance and markets", description: "iFarmer is an agritech platform providing Bangladesh's farmers with financing, quality inputs, and direct market access through a mobile app, serving over 200,000 farmers.", logo: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=200", industry: "Agritech", stage: "Seed", founded: "2019", location: "Dhaka", founders: ["Fahad Ifaz"], funding: "$3M", website: "https://ifarmer.asia" },
  { name: "Truck Lagbe", slug: "truck-lagbe", tagline: "Digitizing Bangladesh's trucking industry", description: "Truck Lagbe is a digital marketplace connecting shippers with truck owners, reducing empty miles by 30% and improving earnings for truck owners across Bangladesh.", logo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200", industry: "Logistics", stage: "Series A", founded: "2018", location: "Dhaka", founders: ["Md. Rahat Ahmed"], funding: "$8M", website: "https://trucklagbe.com" },
  { name: "Shajgoj", slug: "shajgoj", tagline: "Bangladesh's premier beauty e-commerce platform", description: "Shajgoj is Bangladesh's leading beauty and personal care e-commerce platform, offering thousands of local and international products with editorial content and community features.", logo: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200", industry: "E-commerce", stage: "Series A", founded: "2012", location: "Dhaka", founders: ["Rayana Hossain"], funding: "$4M", website: "https://shajgoj.com" },
  { name: "Nagad", slug: "nagad", tagline: "Digital financial service for every Bangladeshi", description: "Nagad is Bangladesh Post Office's digital financial service that grew to 80 million users in 4 years, offering mobile banking with the lowest transaction fees in the market.", logo: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200", industry: "Fintech", stage: "Growth", founded: "2019", location: "Dhaka", founders: ["Nazrul Islam Khan"], funding: "$50M", website: "https://nagad.com.bd" },
  { name: "SSL Wireless", slug: "ssl-wireless", tagline: "Bangladesh's digital payment infrastructure backbone", description: "SSL Wireless has been building Bangladesh's digital payment infrastructure since 2000, processing billions of taka in transactions annually for banks, corporations, and government.", logo: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200", industry: "Fintech", stage: "Growth", founded: "2000", location: "Dhaka", founders: ["Syed Mahbubur Rahman"], funding: "$20M", website: "https://sslwireless.com" },
  { name: "NovaPay", slug: "novapay", tagline: "Next-gen embedded finance for Bangladeshi SMEs", description: "NovaPay is building embedded finance infrastructure for SMEs across Bangladesh, enabling businesses to offer financial services to their customers without a banking license.", logo: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200", industry: "Fintech", stage: "Series A", founded: "2023", location: "Dhaka", founders: ["Arif Hossain", "Priya Das"], funding: "$3.2M", website: "#" },
  { name: "MediLink BD", slug: "medilink-bd", tagline: "Healthcare at your fingertips across Bangladesh", description: "MediLink BD is a telemedicine and health records platform connecting patients with doctors across Bangladesh, making quality healthcare accessible to all.", logo: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200", industry: "Healthtech", stage: "Series A", founded: "2022", location: "Dhaka", founders: ["Dr. Nasrin Akter", "Imran Chowdhury"], funding: "$5.1M", website: "#" },
  { name: "LogiX", slug: "logix", tagline: "Last-mile delivery reimagined with electric vehicles", description: "LogiX is a smart logistics network using micro-warehouses and electric vehicles for same-day delivery across Bangladesh's major cities, reducing carbon emissions by 60%.", logo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200", industry: "Logistics", stage: "Series B", founded: "2021", location: "Dhaka", founders: ["Mahbub Alam", "Tania Begum"], funding: "$12M", website: "#" },
  { name: "SolarBD", slug: "solarbd", tagline: "Clean energy for every home in Bangladesh", description: "SolarBD provides pay-as-you-go solar energy solutions for off-grid communities in rural Bangladesh, bringing clean electricity to over 100,000 households.", logo: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=200", industry: "Cleantech", stage: "Series A", founded: "2022", location: "Khulna", founders: ["Rezaul Karim"], funding: "$4.5M", website: "#" },
];

export async function GET() {
  try {
    await connectDB();
    await Startup.deleteMany({});
    await Startup.insertMany(startups);
    return NextResponse.json({ success: true, count: startups.length });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
