import { Article, Founder, Startup, Idea } from "./types";

export const articles: Article[] = [
  {
    id: "1",
    title: "How Bkash Transformed Bangladesh's Financial Landscape",
    slug: "bkash-transformed-bangladesh-financial-landscape",
    excerpt: "From a small mobile banking startup to serving over 60 million users, bKash's journey is a masterclass in fintech innovation.",
    content: "",
    category: "Fintech",
    author: "Rahim Chowdhury",
    authorAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
    coverImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    publishedAt: "2026-04-08",
    readTime: 6,
    featured: true,
    tags: ["fintech", "mobile banking", "startup"],
  },
  {
    id: "2",
    title: "Shohoz: Redefining Urban Mobility in Dhaka",
    slug: "shohoz-redefining-urban-mobility-dhaka",
    excerpt: "How a ticketing platform evolved into Bangladesh's leading ride-sharing and logistics super-app.",
    content: "",
    category: "Mobility",
    author: "Nadia Islam",
    authorAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
    coverImage: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800",
    publishedAt: "2026-04-06",
    readTime: 5,
    featured: true,
    tags: ["mobility", "ride-sharing", "logistics"],
  },
  {
    id: "3",
    title: "The Rise of Agritech Startups in Rural Bangladesh",
    slug: "rise-agritech-startups-rural-bangladesh",
    excerpt: "Young entrepreneurs are using technology to solve age-old agricultural challenges, connecting farmers directly to markets.",
    content: "",
    category: "Agritech",
    author: "Karim Hossain",
    authorAvatar: "https://randomuser.me/api/portraits/men/55.jpg",
    coverImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800",
    publishedAt: "2026-04-04",
    readTime: 7,
    featured: false,
    tags: ["agritech", "farming", "rural"],
  },
  {
    id: "4",
    title: "10X Ventures: The VC Firm Betting Big on BD Founders",
    slug: "10x-ventures-vc-firm-betting-bd-founders",
    excerpt: "A new wave of local venture capital is emerging, and it's changing how Bangladeshi startups get funded.",
    content: "",
    category: "Investment",
    author: "Sadia Rahman",
    authorAvatar: "https://randomuser.me/api/portraits/women/28.jpg",
    coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800",
    publishedAt: "2026-04-02",
    readTime: 4,
    featured: false,
    tags: ["venture capital", "investment", "funding"],
  },
  {
    id: "5",
    title: "E-commerce Boom: How Chaldal Changed Grocery Shopping",
    slug: "chaldal-changed-grocery-shopping-bangladesh",
    excerpt: "Delivering groceries in under an hour in Dhaka — Chaldal's operational excellence is a blueprint for emerging market e-commerce.",
    content: "",
    category: "E-commerce",
    author: "Tanvir Ahmed",
    authorAvatar: "https://randomuser.me/api/portraits/men/67.jpg",
    coverImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800",
    publishedAt: "2026-03-30",
    readTime: 5,
    featured: false,
    tags: ["e-commerce", "grocery", "logistics"],
  },
  {
    id: "6",
    title: "Women Entrepreneurs Breaking Barriers in Bangladesh",
    slug: "women-entrepreneurs-breaking-barriers-bangladesh",
    excerpt: "Meet the fearless women founders who are reshaping industries and inspiring the next generation.",
    content: "",
    category: "Leadership",
    author: "Farhana Begum",
    authorAvatar: "https://randomuser.me/api/portraits/women/61.jpg",
    coverImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800",
    publishedAt: "2026-03-28",
    readTime: 8,
    featured: false,
    tags: ["women", "leadership", "diversity"],
  },
];

export const founders: Founder[] = [
  {
    id: "1",
    name: "Kamal Quadir",
    slug: "kamal-quadir",
    title: "CEO & Co-Founder",
    company: "bKash",
    industry: "Fintech",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200",
    bio: "Kamal Quadir is a pioneer in mobile financial services, transforming how millions of Bangladeshis access banking.",
    netWorth: "$500M+",
    founded: "2011",
    location: "Dhaka",
    achievements: ["Forbes Asia 30 Under 30", "World Economic Forum Young Global Leader", "MIT Technology Review Innovator"],
    socialLinks: { linkedin: "#", twitter: "#", website: "#" },
    rank: 1,
  },
  {
    id: "2",
    name: "Maliha Quadir",
    slug: "maliha-quadir",
    title: "Founder & CEO",
    company: "Shohoz",
    industry: "Mobility",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200",
    bio: "Maliha Quadir built Shohoz from a bus ticketing platform into Bangladesh's leading mobility super-app.",
    netWorth: "$200M+",
    founded: "2014",
    location: "Dhaka",
    achievements: ["TIME 100 Next", "Goldman Sachs 100 Most Intriguing Entrepreneurs", "GSMA Mobile 100"],
    socialLinks: { linkedin: "#", twitter: "#" },
    rank: 2,
  },
  {
    id: "3",
    name: "Waseem Alim",
    slug: "waseem-alim",
    title: "Co-Founder & CEO",
    company: "Chaldal",
    industry: "E-commerce",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    coverImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200",
    bio: "Waseem Alim co-founded Chaldal, Bangladesh's first and largest online grocery delivery platform.",
    netWorth: "$150M+",
    founded: "2013",
    location: "Dhaka",
    achievements: ["Y Combinator Alumni", "IFC Investment Portfolio", "Best E-commerce Platform BD 2024"],
    socialLinks: { linkedin: "#", website: "#" },
    rank: 3,
  },
  {
    id: "4",
    name: "Shafiq Islam",
    slug: "shafiq-islam",
    title: "Founder & CEO",
    company: "Pathao",
    industry: "Super App",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    coverImage: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=1200",
    bio: "Shafiq Islam turned Pathao into Bangladesh's most-used super app, covering rides, food, and payments.",
    netWorth: "$300M+",
    founded: "2015",
    location: "Dhaka",
    achievements: ["Sequoia-backed Founder", "Best Startup South Asia 2023", "BD Tech Icon Award"],
    socialLinks: { linkedin: "#", twitter: "#", website: "#" },
    rank: 4,
  },
  {
    id: "5",
    name: "Aisha Sultana",
    slug: "aisha-sultana",
    title: "Founder & CTO",
    company: "AgroShift",
    industry: "Agritech",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    coverImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200",
    bio: "Aisha Sultana is revolutionizing Bangladesh's agricultural supply chain using AI and IoT.",
    netWorth: "$50M+",
    founded: "2020",
    location: "Sylhet",
    achievements: ["MIT Solve Winner 2024", "Google for Startups Accelerator", "UN SDG Champion"],
    socialLinks: { linkedin: "#", twitter: "#" },
    rank: 5,
  },
  {
    id: "6",
    name: "Rashed Khan",
    slug: "rashed-khan",
    title: "Co-Founder & CEO",
    company: "ShikhoTech",
    industry: "Edtech",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    coverImage: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200",
    bio: "Rashed Khan is making quality education accessible to every student in Bangladesh through technology.",
    netWorth: "$80M+",
    founded: "2019",
    location: "Dhaka",
    achievements: ["Reach Capital Portfolio", "Best Edtech BD 2025", "30 Under 30 Asia"],
    socialLinks: { linkedin: "#", website: "#" },
    rank: 6,
  },
];

export const startups: Startup[] = [
  {
    id: "1",
    name: "NovaPay",
    slug: "novapay",
    tagline: "Next-gen digital payments for Bangladesh",
    description: "NovaPay is building embedded finance infrastructure for SMEs across Bangladesh.",
    logo: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200",
    industry: "Fintech",
    stage: "Series A",
    founded: "2023",
    location: "Dhaka",
    founders: ["Arif Hossain", "Priya Das"],
    funding: "$3.2M",
    website: "#",
  },
  {
    id: "2",
    name: "GreenHarvest",
    slug: "greenharvest",
    tagline: "Connecting farmers to global markets",
    description: "AI-powered platform that helps Bangladeshi farmers get fair prices and access export markets.",
    logo: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=200",
    industry: "Agritech",
    stage: "Seed",
    founded: "2024",
    location: "Rajshahi",
    founders: ["Fatema Khatun"],
    funding: "$800K",
    website: "#",
  },
  {
    id: "3",
    name: "MediLink BD",
    slug: "medilink-bd",
    tagline: "Healthcare at your fingertips",
    description: "Telemedicine and health records platform connecting patients with doctors across Bangladesh.",
    logo: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200",
    industry: "Healthtech",
    stage: "Series A",
    founded: "2022",
    location: "Dhaka",
    founders: ["Dr. Nasrin Akter", "Imran Chowdhury"],
    funding: "$5.1M",
    website: "#",
  },
  {
    id: "4",
    name: "EduVerse",
    slug: "eduverse",
    tagline: "Immersive learning for the next generation",
    description: "VR/AR-based educational content platform for Bangladeshi students from grade 1 to 12.",
    logo: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200",
    industry: "Edtech",
    stage: "Pre-seed",
    founded: "2025",
    location: "Chittagong",
    founders: ["Sabbir Rahman"],
    funding: "$250K",
    website: "#",
  },
  {
    id: "5",
    name: "LogiX",
    slug: "logix",
    tagline: "Last-mile delivery, reimagined",
    description: "Smart logistics network using micro-warehouses and electric vehicles for same-day delivery.",
    logo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200",
    industry: "Logistics",
    stage: "Series B",
    founded: "2021",
    location: "Dhaka",
    founders: ["Mahbub Alam", "Tania Begum"],
    funding: "$12M",
    website: "#",
  },
  {
    id: "6",
    name: "SolarBD",
    slug: "solarbd",
    tagline: "Clean energy for every home",
    description: "Pay-as-you-go solar energy solutions for off-grid communities in rural Bangladesh.",
    logo: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=200",
    industry: "Cleantech",
    stage: "Series A",
    founded: "2022",
    location: "Khulna",
    founders: ["Rezaul Karim"],
    funding: "$4.5M",
    website: "#",
  },
];

export const ideas: Idea[] = [
  {
    id: "1",
    title: "AI-Powered Flood Early Warning System",
    description: "Using satellite data and ML to predict floods 72 hours in advance and alert rural communities via SMS.",
    submittedBy: "Tanvir Hossain",
    votes: 2847,
    month: "April 2026",
    winner: true,
    category: "ClimaTech",
  },
  {
    id: "2",
    title: "Micro-Insurance for Rickshaw Pullers",
    description: "Affordable daily micro-insurance for informal workers, paid via mobile money in small increments.",
    submittedBy: "Nasreen Akter",
    votes: 2103,
    month: "April 2026",
    winner: false,
    category: "Fintech",
  },
  {
    id: "3",
    title: "Garment Worker Skill Marketplace",
    description: "Platform connecting skilled garment workers with global fashion brands for remote quality control roles.",
    submittedBy: "Karim Uddin",
    votes: 1876,
    month: "April 2026",
    winner: false,
    category: "Future of Work",
  },
];
