import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { Founder } from "@/lib/models/Founder";

export const dynamic = "force-dynamic";

const founders = [
  { name: "Kamal Quadir", slug: "kamal-quadir", title: "CEO & Co-Founder", company: "bKash", industry: "Fintech", avatar: "https://randomuser.me/api/portraits/men/1.jpg", coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200", bio: "Kamal Quadir is a pioneer in mobile financial services, transforming how millions of Bangladeshis access banking. Under his leadership, bKash grew to serve over 65 million users, making it one of the world's largest mobile money platforms.", netWorth: "$500M+", founded: "2011", location: "Dhaka", achievements: ["Forbes Asia 30 Under 30", "World Economic Forum Young Global Leader", "MIT Technology Review Innovator"], socialLinks: { linkedin: "#", twitter: "#", website: "#" }, rank: 1 },
  { name: "Maliha Quadir", slug: "maliha-quadir", title: "Founder & CEO", company: "Shohoz", industry: "Mobility", avatar: "https://randomuser.me/api/portraits/women/2.jpg", coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200", bio: "Maliha Quadir built Shohoz from a bus ticketing platform into Bangladesh's leading mobility super-app. Her vision of accessible transportation has transformed how millions of Bangladeshis move around cities.", netWorth: "$200M+", founded: "2014", location: "Dhaka", achievements: ["TIME 100 Next", "Goldman Sachs 100 Most Intriguing Entrepreneurs", "GSMA Mobile 100"], socialLinks: { linkedin: "#", twitter: "#" }, rank: 2 },
  { name: "Waseem Alim", slug: "waseem-alim", title: "Co-Founder & CEO", company: "Chaldal", industry: "E-commerce", avatar: "https://randomuser.me/api/portraits/men/3.jpg", coverImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200", bio: "Waseem Alim co-founded Chaldal, Bangladesh's first and largest online grocery delivery platform. A Y Combinator alumni, he pioneered the micro-warehouse model that enables under-one-hour delivery across Dhaka.", netWorth: "$150M+", founded: "2013", location: "Dhaka", achievements: ["Y Combinator Alumni", "IFC Investment Portfolio", "Best E-commerce Platform BD 2024"], socialLinks: { linkedin: "#", website: "#" }, rank: 3 },
  { name: "Hussain M Elius", slug: "hussain-m-elius", title: "Co-Founder & CEO", company: "Pathao", industry: "Super App", avatar: "https://randomuser.me/api/portraits/men/4.jpg", coverImage: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=1200", bio: "Hussain M Elius turned Pathao into Bangladesh's most-used super app, covering rides, food delivery, and digital payments. His entrepreneurial journey from courier service to super app is a blueprint for emerging market startups.", netWorth: "$300M+", founded: "2015", location: "Dhaka", achievements: ["Sequoia-backed Founder", "Best Startup South Asia 2023", "BD Tech Icon Award"], socialLinks: { linkedin: "#", twitter: "#", website: "#" }, rank: 4 },
  { name: "Aisha Sultana", slug: "aisha-sultana", title: "Founder & CTO", company: "AgroShift", industry: "Agritech", avatar: "https://randomuser.me/api/portraits/women/5.jpg", coverImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200", bio: "Aisha Sultana is revolutionizing Bangladesh's agricultural supply chain using AI and IoT. Her platform connects 500,000 farmers directly to markets, eliminating middlemen and increasing farmer incomes by up to 40%.", netWorth: "$50M+", founded: "2020", location: "Sylhet", achievements: ["MIT Solve Winner 2024", "Google for Startups Accelerator", "UN SDG Champion"], socialLinks: { linkedin: "#", twitter: "#" }, rank: 5 },
  { name: "Rashed Khan", slug: "rashed-khan", title: "Co-Founder & CEO", company: "ShikhoTech", industry: "Edtech", avatar: "https://randomuser.me/api/portraits/men/6.jpg", coverImage: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200", bio: "Rashed Khan is making quality education accessible to every student in Bangladesh through technology. ShikhoTech serves over 3 million students with personalized learning experiences.", netWorth: "$80M+", founded: "2019", location: "Dhaka", achievements: ["Reach Capital Portfolio", "Best Edtech BD 2025", "30 Under 30 Asia"], socialLinks: { linkedin: "#", website: "#" }, rank: 6 },
  { name: "Afeef Zaman", slug: "afeef-zaman", title: "Co-Founder & CEO", company: "ShopUp", industry: "B2B Tech", avatar: "https://randomuser.me/api/portraits/men/7.jpg", coverImage: "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=1200", bio: "Afeef Zaman is digitizing Bangladesh's 10 million small retailers through ShopUp's B2B commerce platform. The company has raised over $75 million and is expanding across South Asia.", netWorth: "$120M+", founded: "2018", location: "Dhaka", achievements: ["Tiger Global Portfolio", "Forbes 30 Under 30 Asia", "Best B2B Startup BD"], socialLinks: { linkedin: "#", twitter: "#" }, rank: 7 },
  { name: "Ivy Huq Russell", slug: "ivy-huq-russell", title: "Founder & CEO", company: "Maya", industry: "Healthtech", avatar: "https://randomuser.me/api/portraits/women/8.jpg", coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200", bio: "Ivy Huq Russell founded Maya, an AI-powered health assistant serving over 5 million Bangladeshis with free medical advice. Her platform has become a critical healthcare resource, especially for women in rural areas.", netWorth: "$40M+", founded: "2016", location: "Dhaka", achievements: ["Skoll Foundation Award", "USAID Innovation Award", "Women in Tech BD 2024"], socialLinks: { linkedin: "#", twitter: "#", website: "#" }, rank: 8 },
  { name: "Fahad Ifaz", slug: "fahad-ifaz", title: "Co-Founder & CEO", company: "iFarmer", industry: "Agritech", avatar: "https://randomuser.me/api/portraits/men/9.jpg", coverImage: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200", bio: "Fahad Ifaz is transforming Bangladesh's agricultural sector through iFarmer's digital platform that provides farmers with financing, inputs, and market access. The platform has served over 200,000 farmers.", netWorth: "$30M+", founded: "2019", location: "Dhaka", achievements: ["Acumen Fellow", "GSMA Ecosystem Accelerator", "Best Agritech Startup 2024"], socialLinks: { linkedin: "#" }, rank: 9 },
  { name: "Rayana Hossain", slug: "rayana-hossain", title: "Founder & CEO", company: "Shajgoj", industry: "E-commerce", avatar: "https://randomuser.me/api/portraits/women/10.jpg", coverImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200", bio: "Rayana Hossain built Shajgoj from a beauty blog into Bangladesh's premier beauty e-commerce platform. Her company has empowered thousands of women entrepreneurs and serves millions of customers.", netWorth: "$25M+", founded: "2012", location: "Dhaka", achievements: ["IFC Women Entrepreneur Award", "Best E-commerce BD 2023", "Forbes Women in Business"], socialLinks: { linkedin: "#", twitter: "#" }, rank: 10 },
  { name: "Md. Rahat Ahmed", slug: "md-rahat-ahmed", title: "Founder & CEO", company: "Truck Lagbe", industry: "Logistics", avatar: "https://randomuser.me/api/portraits/men/11.jpg", coverImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200", bio: "Md. Rahat Ahmed is digitizing Bangladesh's $8 billion trucking industry through Truck Lagbe's marketplace platform. The company has connected thousands of shippers with truck owners, reducing empty miles by 30%.", netWorth: "$20M+", founded: "2018", location: "Dhaka", achievements: ["Y Combinator W20", "Best Logistics Startup BD", "Startup World Cup Finalist"], socialLinks: { linkedin: "#", website: "#" }, rank: 11 },
  { name: "Ayman Sadiq", slug: "ayman-sadiq", title: "Founder & CEO", company: "10 Minute School", industry: "Edtech", avatar: "https://randomuser.me/api/portraits/men/12.jpg", coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200", bio: "Ayman Sadiq started 10 Minute School with a Facebook page and a dream to democratize education in Bangladesh. Today it is the country's largest online education platform with over 7 million registered students.", netWorth: "$60M+", founded: "2015", location: "Dhaka", achievements: ["Queen's Young Leader Award", "Diana Award", "Time Next Generation Leader"], socialLinks: { linkedin: "#", twitter: "#", website: "#" }, rank: 12 },
  { name: "Syed Mahbubur Rahman", slug: "syed-mahbubur-rahman", title: "Founder & CEO", company: "SSL Wireless", industry: "Fintech", avatar: "https://randomuser.me/api/portraits/men/13.jpg", coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200", bio: "Syed Mahbubur Rahman built SSL Wireless into the backbone of Bangladesh's digital payment infrastructure. For over two decades, his company has enabled billions of digital transactions across the country.", netWorth: "$90M+", founded: "2000", location: "Dhaka", achievements: ["ICT Business Award BD", "Digital Bangladesh Pioneer", "BASIS National ICT Award"], socialLinks: { linkedin: "#" }, rank: 13 },
  { name: "Tejas Viswanath", slug: "tejas-viswanath", title: "Co-Founder & COO", company: "Chaldal", industry: "E-commerce", avatar: "https://randomuser.me/api/portraits/men/14.jpg", coverImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200", bio: "Tejas Viswanath co-founded Chaldal and built its operational excellence that enables under-one-hour grocery delivery. His engineering background helped create the micro-warehouse model now being replicated across emerging markets.", netWorth: "$100M+", founded: "2013", location: "Dhaka", achievements: ["Y Combinator Alumni", "MIT Innovator Under 35", "Best COO Award BD"], socialLinks: { linkedin: "#", twitter: "#" }, rank: 14 },
  { name: "Nazrul Islam Khan", slug: "nazrul-islam-khan", title: "Founder & Chairman", company: "Nagad", industry: "Fintech", avatar: "https://randomuser.me/api/portraits/men/15.jpg", coverImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200", bio: "Nazrul Islam Khan founded Third Wave Technologies and partnered with Bangladesh Post Office to launch Nagad, which grew to 80 million users in just 4 years. His vision disrupted the mobile financial services market.", netWorth: "$150M+", founded: "2019", location: "Dhaka", achievements: ["Digital Bangladesh Award", "Best Fintech Innovation 2023", "National ICT Award"], socialLinks: { linkedin: "#" }, rank: 15 },
];

export async function GET() {
  try {
    await connectDB();
    await Founder.deleteMany({});
    await Founder.insertMany(founders);
    return NextResponse.json({ success: true, count: founders.length });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
